Axonivy-express
axonivy-market/axonivy-express pull request #1
Opened 2023-08-22 02:13 UTC by phhung-axonivy

2023-08-30 12:10 UTC, andreasbalsiger requested changes
see comments

2023-08-30 12:10 UTC, andreasbalsiger commented on axonivy-express-product/README.md
> +   * The Powerful Toolset allows you to create processes, define different task types, set responsibilities and due dates and define user dialogs for each task.
My input is as follows:
Axon Ivy Express is an add-on module for the Axon Ivy Portal. As a business user, it enables you to create and share your process applications with your colleagues. These capabilities are also known as No-Code Application Platforms or Citizen Developer Platforms. Therefore, it is the perfect tool to digitize your processes and create standardization, reliability, and traceability. Axon Ivy Express:

   * allows business users to create processes without an IT background.
   * automates business processes without IT department involvement.
   * supports all standard features such as email notifications, task delegation, etc.
   * features an importer tool to hand over your No-Code business processes to Low-Code or Pro-Code developers.

2023-10-09 07:49 UTC, pvthai-axonivy commented
Hi @andreasbalsiger @phhung-axonivy I resolved all comments. Please take a look. Thank you!

2023-10-10 07:04 UTC, phhung-axonivy commented
Hi @nqhoan-axonivy,
pvthai resolved all comments of reviewers.
Could you help me to merge this pull request?

2023-10-26 02:01 UTC, phhung-axonivy commented
Hi @andreasbalsiger,
Could you help me review the changes from @pvthai-axonivy?
If it's good, please approve this pull request.

2023-10-27 13:59 UTC, andreasbalsiger commented
all good

2023-10-27 13:59 UTC, closed without merging